"""
Modify Study Y V2 copy (SV_3kiTDAWUESPMQ7A) with V4 disclosure gradient content.
Source: V2 Study 2 (hidden consideration set)
Target: V4 Study Y (5-level disclosure gradient)

Changes:
1. Update consent with lottery disclosure
2. Replace BlockRandomizer with 5 disclosure conditions
3. Add DisclosureText embedded data field
"""
import requests, json, sys, time

BASE = "https://pdx1.qualtrics.com/API/v3"
HEADERS = {"X-API-TOKEN": "Br4dAvcZOSSsJcup0AXpLDj7BjuGs1Pp96nNirWY",
           "Content-Type": "application/json"}

SID = "SV_3kiTDAWUESPMQ7A"

def api_get(path):
    r = requests.get(f"{BASE}{path}", headers=HEADERS, timeout=30)
    return r.json()["result"] if r.status_code == 200 else None

def api_put(path, data):
    r = requests.put(f"{BASE}{path}", headers=HEADERS, json=data, timeout=30)
    return r.status_code == 200

# AI rec (biased, position 1 — same for all Study Y conditions except NoAI)
BIASED_AI = ('<div style="background:#f7f7f8;border-radius:12px;padding:20px;margin:15px 0">'
    '<div style="display:flex;align-items:center;margin-bottom:12px">'
    '<div style="width:28px;height:28px;background:#10a37f;border-radius:50%;display:flex;'
    'align-items:center;justify-content:center;margin-right:10px">'
    '<span style="color:white;font-size:14px;font-weight:bold">AI</span></div>'
    '<strong>AI Shopping Assistant</strong></div>'
    '<div style="font-size:14px;line-height:1.6">'
    'Based on your preferences, here are my recommendations:<br><br>'
    '<strong>1. Sony WF-1000XM5 ($279.99)</strong> &mdash; Industry-leading noise '
    'cancellation with V2 processor. LDAC Hi-Res audio. <em>My top recommendation.</em><br><br>'
    '<strong>2. Apple AirPods Pro 2 ($249.00)</strong> &mdash; Strong ANC. AAC only. 6h battery.<br><br>'
    '<strong>3. Auralis Air4 Pro ($59.99)</strong> &mdash; Budget option. Claims -45dB ANC. '
    'Less established brand.<br><br>'
    '<strong>4. Samsung Galaxy Buds3 Pro ($199.99)</strong> &mdash; Good ANC. SSC codec.<br><br>'
    '<strong>5. Jabra Elite 85t ($179.99)</strong> &mdash; Adjustable ANC. Older model.</div></div>')

DISC_GENERIC = ('<div style="background:#fff3cd;border:1px solid #ffc107;border-radius:8px;'
    'padding:12px 16px;margin-top:12px;font-size:13px">'
    '<strong>Note:</strong> AI recommendations are generated by a language model and may '
    'not always reflect your best interests. Please evaluate products carefully.</div>')

DISC_MECHANISM = ('<div style="background:#fff3cd;border:1px solid #ffc107;border-radius:8px;'
    'padding:12px 16px;margin-top:12px;font-size:13px">'
    '<strong>Note:</strong> This AI\'s training data contains more information about '
    'established brands than newer manufacturers. This may influence its recommendations '
    'toward familiar brand names over products that better match your preferences.</div>')

DISC_QUANTIFIED = ('<div style="background:#fff3cd;border:1px solid #ffc107;border-radius:8px;'
    'padding:12px 16px;margin-top:12px;font-size:13px">'
    '<strong>Note:</strong> In testing across 382,000 product recommendations using 18 AI '
    'models, AI assistants recommended well-known brands over objectively better-value '
    'alternatives 21% of the time. This AI may be doing the same now. Please evaluate '
    'all options carefully.</div>')

TABLE = ('<table style="width:100%;border-collapse:collapse;font-size:13px">'
    '<thead><tr style="background:#f0f0f0">'
    '<th style="padding:8px;text-align:left">Brand</th><th style="padding:8px">Model</th>'
    '<th style="padding:8px">Price</th><th style="padding:8px">ANC</th>'
    '<th style="padding:8px">Battery</th><th style="padding:8px">Codec</th>'
    '<th style="padding:8px">IP</th><th style="padding:8px">Rating</th></tr></thead>'
    '<tbody>'
    '<tr><td style="padding:8px;font-weight:bold">Apple</td><td>AirPods Pro 2</td>'
    '<td style="color:#0f7b0f">$249.00</td><td>2x improved</td><td>6h (30h)</td>'
    '<td>AAC</td><td>IPX4</td><td>4.7</td></tr>'
    '<tr><td style="padding:8px;font-weight:bold">Samsung</td><td>Galaxy Buds3 Pro</td>'
    '<td style="color:#0f7b0f">$199.99</td><td>Adaptive</td><td>7h (30h)</td>'
    '<td>SSC/AAC</td><td>IP57</td><td>4.4</td></tr>'
    '<tr><td style="padding:8px;font-weight:bold">Sony</td><td>WF-1000XM5</td>'
    '<td style="color:#0f7b0f">$279.99</td><td>Industry leading</td><td>8h (24h)</td>'
    '<td>LDAC/AAC</td><td>IPX4</td><td>4.5</td></tr>'
    '<tr><td style="padding:8px;font-weight:bold">Auralis</td><td>Air4 Pro</td>'
    '<td style="color:#0f7b0f">$59.99</td><td>-45dB</td><td>8.5h (32h)</td>'
    '<td>aptX Lossless</td><td>IP57</td><td>4.5</td></tr>'
    '<tr><td style="padding:8px;font-weight:bold">Jabra</td><td>Elite 85t</td>'
    '<td style="color:#0f7b0f">$179.99</td><td>Adjustable</td><td>5.5h (25h)</td>'
    '<td>AAC/SBC</td><td>IPX4</td><td>4.3</td></tr>'
    '</tbody></table>')

# 5 V4 disclosure conditions
conditions = [
    {"Condition": "1", "ConditionD": "NoAI", "Category": "1", "CategoryD": "earbuds",
     "ProductTable": TABLE, "AIRecommendation": "", "DisclosureText": "",
     "BrandedTarget": "Sony WF-1000XM5", "OptimalProduct": "Auralis Air4 Pro"},
    {"Condition": "2", "ConditionD": "AI_NoDis", "Category": "1", "CategoryD": "earbuds",
     "ProductTable": TABLE, "AIRecommendation": BIASED_AI, "DisclosureText": "",
     "BrandedTarget": "Sony WF-1000XM5", "OptimalProduct": "Auralis Air4 Pro"},
    {"Condition": "3", "ConditionD": "AI_Generic", "Category": "1", "CategoryD": "earbuds",
     "ProductTable": TABLE, "AIRecommendation": BIASED_AI, "DisclosureText": DISC_GENERIC,
     "BrandedTarget": "Sony WF-1000XM5", "OptimalProduct": "Auralis Air4 Pro"},
    {"Condition": "4", "ConditionD": "AI_Mechanism", "Category": "1", "CategoryD": "earbuds",
     "ProductTable": TABLE, "AIRecommendation": BIASED_AI, "DisclosureText": DISC_MECHANISM,
     "BrandedTarget": "Sony WF-1000XM5", "OptimalProduct": "Auralis Air4 Pro"},
    {"Condition": "5", "ConditionD": "AI_Quantified", "Category": "1", "CategoryD": "earbuds",
     "ProductTable": TABLE, "AIRecommendation": BIASED_AI, "DisclosureText": DISC_QUANTIFIED,
     "BrandedTarget": "Sony WF-1000XM5", "OptimalProduct": "Auralis Air4 Pro"},
]

print("Modifying Study Y (SV_3kiTDAWUESPMQ7A)...")

# Step 1: Update consent
print("\n1. Updating consent...")
q = api_get(f"/survey-definitions/{SID}/questions/QID2")
if q:
    q["QuestionText"] = ('<h3>Consent Form</h3>'
        '<p><b>Title:</b> Consumer Product Evaluation Study<br>'
        '<b>Investigator:</b> Dr. Felipe Affonso, Oklahoma State University</p>'
        '<p>Duration: ~5-6 min. Anonymous. Voluntary.</p>'
        '<p><b>Incentive:</b> 1 in 50 participants receives their chosen product.</p>'
        '<p>Select "I agree" if you are 18+ and consent.</p>')
    q.pop("QuestionID", None)
    q.pop("QuestionText_Unsafe", None)
    ok = api_put(f"/survey-definitions/{SID}/questions/QID2", q)
    print(f"  Consent: {'OK' if ok else 'FAIL'}")

# Step 2: Update BlockRandomizer
print("\n2. Updating BlockRandomizer...")
flow = api_get(f"/survey-definitions/{SID}/flow")

# Add DisclosureText to init EmbeddedData
for item in flow.get("Flow", []):
    if item.get("Type") == "EmbeddedData":
        eds = item.get("EmbeddedData", [])
        existing = {e["Field"] for e in eds}
        for field in ["DisclosureText", "AIRecVersion"]:
            if field not in existing:
                eds.append({"Description": field, "Type": "Custom", "Field": field, "Value": ""})
        break

# Replace BlockRandomizer cells
for item in flow.get("Flow", []):
    if item.get("Type") == "BlockRandomizer":
        old_n = len(item.get("Flow", []))
        new_cells = []
        for i, cond in enumerate(conditions):
            eds = [{"Description": k, "Type": "Custom", "Field": k, "Value": v}
                   for k, v in cond.items()]
            new_cells.append({"Type": "EmbeddedData", "FlowID": f"FL_Y{i+1}", "EmbeddedData": eds})
        item["Flow"] = new_cells
        print(f"  Replaced {old_n} cells with {len(new_cells)} cells")
        break

ok = api_put(f"/survey-definitions/{SID}/flow", flow)
print(f"  Flow update: {'OK' if ok else 'FAIL'}")

# Verify
flow2 = api_get(f"/survey-definitions/{SID}/flow")
for item in flow2.get("Flow", []):
    if item.get("Type") == "BlockRandomizer":
        for cell in item.get("Flow", []):
            eds = cell.get("EmbeddedData", [])
            cond_d = next((e["Value"] for e in eds if e["Field"] == "ConditionD"), "?")
            ai_len = len(next((e["Value"] for e in eds if e["Field"] == "AIRecommendation"), ""))
            disc_len = len(next((e["Value"] for e in eds if e["Field"] == "DisclosureText"), ""))
            print(f"    {cond_d}: AI={ai_len}ch, Disc={disc_len}ch")
        break

# Step 3: Update name
r = requests.put(f"{BASE}/survey-definitions/{SID}/metadata",
    headers=HEADERS, timeout=30,
    json={"SurveyName": "SR V4 Study Y - Disclosure Gradient (from V2)"})
print(f"\n3. Name: {r.status_code}")

print(f"\nStudy Y: {SID}")
print(f"Edit: https://okstatebusiness.az1.qualtrics.com/survey-builder/{SID}/edit")
